// Strait of Hormuz daily shipping crossings
// Auto-generated by pipeline - do not edit directly

export interface HormuzEntry {
  date: string
  daily: number
  label: string
  note: string
}

const data: HormuzEntry[] = [
  { "date": "2026-02-21", "daily": 20, "label": "Pre-war avg ~20/day", "note": "Normal traffic before escalation" },
  { "date": "2026-02-28", "daily": 0, "label": "War begins — zero traffic", "note": "First strikes, complete shutdown" },
  { "date": "2026-03-01", "daily": 2, "label": "Near-total halt", "note": "Only military/Iranian-flagged vessels" },
  { "date": "2026-03-04", "daily": 0, "label": "Strait closed", "note": "Iran formally declares closure" },
  { "date": "2026-03-06", "daily": 2, "label": "Tugboat Mussafah 2 sunk", "note": "Iran-allowed exceptions only" },
  { "date": "2026-03-11", "daily": 1, "label": "Mass tanker attacks", "note": "Mayuree Naree, Vishnu, Zefyros" },
  { "date": "2026-03-15", "daily": 4, "label": "Trickle resumes", "note": "Sanctioned/Iranian vessels only" },
  { "date": "2026-03-27", "daily": 2, "label": "Expanded ban", "note": "Closed to US/Israel/allies" },
  { "date": "2026-04-01", "daily": 5, "label": "April avg: 6.4/day", "note": "191 vessels entire month (Kpler/CNN)" },
  { "date": "2026-04-08", "daily": 5, "label": "Ceasefire agreed", "note": "Strait to reopen - failed" },
  { "date": "2026-04-13", "daily": 3, "label": "US blockade begins", "note": "Dual blockade - US blocks Iran" },
  { "date": "2026-04-21", "daily": 4, "label": "20,000 mariners stranded", "note": "2,000 ships stuck in Gulf (IMO)" },
  { "date": "2026-04-30", "daily": 7, "label": "Gradual recovery begins", "note": "Some non-sanctioned vessels test route" },
  { "date": "2026-05-04", "daily": 6, "label": "Project Freedom launched", "note": "US Navy escort operation" },
  { "date": "2026-05-15", "daily": 10, "label": "Steady increase", "note": "Ceasefire diplomacy improving outlook" },
  { "date": "2026-05-29", "daily": 10, "label": "US blockade lifted", "note": "Paving way for MOU" },
  { "date": "2026-06-01", "daily": 12, "label": "Pre-MOU recovery", "note": "Shipowners slowly return" },
  { "date": "2026-06-17", "daily": 18, "label": "Islamabad MOU signed", "note": "Ceasefire — traffic rebounds sharply" },
  { "date": "2026-06-20", "daily": 10, "label": "Iran re-closes strait", "note": "Cites Israeli violations" },
  { "date": "2026-06-25", "daily": 20, "label": "Post-MOU peak", "note": "Near normal levels for ~3 weeks" },
  { "date": "2026-06-30", "daily": 16, "label": "Late June plateau", "note": "30-40/day in early July ahead" },
  { "date": "2026-07-03", "daily": 43, "label": "Kpler: 43 crossings", "note": "July 3 spike (Al Jazeera)" },
  { "date": "2026-07-04", "daily": 34, "label": "Kpler: 34 crossings", "note": "High holiday traffic" },
  { "date": "2026-07-05", "daily": 31, "label": "Kpler: 31 crossings", "note": "Still elevated pre-escalation" },
  { "date": "2026-07-08", "daily": 20, "label": "War resumes — MOU void", "note": "US strikes resume, Iran voids deal" },
  { "date": "2026-07-10", "daily": 15, "label": "Rapid decline", "note": "Shipowners pull back" },
  { "date": "2026-07-14", "daily": 12, "label": "Week avg dropping", "note": "7th consecutive night of US strikes" },
  { "date": "2026-07-15", "daily": 16, "label": "Blockade announced", "note": "Trump reinstates naval blockade" },
  { "date": "2026-07-16", "daily": 8, "label": "Single digits", "note": "Blockade takes effect (Kpler)" },
  { "date": "2026-07-17", "daily": 14, "label": "S&P: 40 vessels Jul 17-19", "note": "~13/day avg" },
  { "date": "2026-07-18", "daily": 13, "label": "Lloyd's: 53/week", "note": "Down 66% from 157 prior week" },
  { "date": "2026-07-19", "daily": 12, "label": "~15% of pre-war", "note": "Lloyd's: tanker/gas down to 30 from 90" },
  { "date": "2026-07-20", "daily": 10, "label": "Sporadic recovery", "note": "Only 1/3 compliant with restrictions" },
  { "date": "2026-07-21", "daily": 9, "label": "Continued low", "note": "Iran strikes Amazon AWS Bahrain" },
  { "date": "2026-07-22", "daily": 8, "label": "Infrastructure war phase", "note": "Bridge-for-ship formula declared" },
  { "date": "2026-07-23", "daily": 7, "label": "12 ships prevented", "note": "CENTCOM interdiction ops" },
  { "date": "2026-07-24", "daily": 6, "label": "LNG tanker disabled", "note": "US disables Iranian tanker in Sea of Oman" }
]

export default data
